# Generated by Django 4.2 on 2023-04-24 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialproperty',
            options={'verbose_name_plural': 'Commercial Properties'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='residentialproperty',
            options={'verbose_name_plural': 'Residential Properties'},
        ),
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 19, 54, 39, 477223)),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='image',
            field=models.ImageField(null=True, upload_to='assets_commercial'),
        ),
    ]
