# Generated by Django 4.2 on 2023-04-24 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_alter_commercialproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 19, 55, 28, 259967)),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='image',
            field=models.ImageField(null=True, upload_to='assets_residential'),
        ),
    ]
