# Generated by Django 4.2 on 2023-04-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
