# Generated by Django 4.2 on 2023-04-25 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_alter_commercialappointment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialproperty',
            options={'verbose_name_plural': 'Properties Commercial'},
        ),
        migrations.AlterModelOptions(
            name='residentialproperty',
            options={'verbose_name_plural': 'Properties Residential'},
        ),
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 5, 20, 56, 43998)),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ResidentialAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 4, 25, 5, 20, 56, 44614))),
                ('residential_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.commercialproperty')),
            ],
            options={
                'verbose_name_plural': 'Appointments Residential',
            },
        ),
    ]
