# Generated by Django 4.2 on 2023-04-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_rename_city_customuser_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
