# Generated by Django 4.2 on 2023-04-25 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_alter_commercialproperty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default=('sale', 'Sale'), max_length=50),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default=('sale', 'Sale'), max_length=50),
        ),
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 5, 37, 5, 1818)),
        ),
        migrations.AlterField(
            model_name='residentialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 5, 37, 5, 2292)),
        ),
    ]
