# Generated by Django 4.2 on 2023-04-25 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_commercialproperty_type_residentialproperty_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 14, 21, 30, 886302)),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='image',
            field=models.ImageField(null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='residentialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 14, 21, 30, 886940)),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='image',
            field=models.ImageField(null=True, upload_to='assets'),
        ),
    ]
