# Generated by Django 4.2 on 2023-04-26 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_alter_commercialappointment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 6, 54, 32, 889199)),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='image',
            field=models.ImageField(null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='residentialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 6, 54, 32, 889842)),
        ),
        migrations.AlterField(
            model_name='residentialproperty',
            name='image',
            field=models.ImageField(null=True, upload_to='assets'),
        ),
    ]
