# Generated by Django 4.2 on 2023-04-26 08:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_alter_commercialappointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialappointment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 8, 54, 59, 585029)),
        ),
        migrations.AlterField(
            model_name='residentialappointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 8, 54, 59, 585425)),
        ),
    ]
