# Generated by Django 4.2 on 2023-04-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_alter_commercialappointment_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialappointment',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='residentialappointment',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='commercialappointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='residentialappointment',
            name='end_time',
        ),
    ]
