# Generated by Django 4.2 on 2023-05-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0012_rename_start_time_commercialappointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialappointment',
            name='residential_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.residentialproperty'),
        ),
    ]
